[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.3.2"
edition = "2024"
license = "MIT OR Apache-2.0"
authors = ["Utkarsha Vardhana"]
repository = "https://github.com/utkarshavardhana/sspur"
homepage = "https://github.com/utkarshavardhana/sspur"
rust-version = "1.88"

[workspace.dependencies]
sspur-syntax = { path = "crates/sspur-syntax" }
sspur-check = { path = "crates/sspur-check" }
sspur-hash = { path = "crates/sspur-hash" }
sspur-eval = { path = "crates/sspur-eval" }
sspur-store = { path = "crates/sspur-store" }
sspur-native = { path = "crates/sspur-native" }
sspur-smt = { path = "crates/sspur-smt" }
sspur-deploy = { path = "crates/sspur-deploy" }
blake3 = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
