pub const GLOBALS: &[&str] = &[
    "log(msg: Str) -> Unit ! log",
    "some[A](x: A) -> Opt[A]",
    "ok[A, E](x: A) -> Res[A, E]",
    "err[A, E](e: E) -> Res[A, E]",
    "empty_map[K, V]() -> Map[K, V]",
    "min[A](a: A, b: A) -> A",
    "max[A](a: A, b: A) -> A",
    "secret[A](x: A) -> Secret[A]",
    "pii[A](x: A) -> Pii[A]",
    "untrusted[A](x: A) -> Untrusted[A]",
    "guess[A](x: A, conf: F64) -> Guess[A]",
];

pub const METHODS: &[(&str, &str)] = &[
    ("List", "len[A](xs: List[A]) -> Int"),
    ("List", "is_empty[A](xs: List[A]) -> Bool"),
    ("List", "map[A, B, e](xs: List[A], f: A -> B ! e) -> List[B] ! e"),
    ("List", "flat_map[A, B, e](xs: List[A], f: A -> List[B] ! e) -> List[B] ! e"),
    ("List", "filter[A, e](xs: List[A], f: A -> Bool ! e) -> List[A] ! e"),
    ("List", "fold[A, B, e](xs: List[A], init: B, f: (B, A) -> B ! e) -> B ! e"),
    ("List", "any[A, e](xs: List[A], f: A -> Bool ! e) -> Bool ! e"),
    ("List", "all[A, e](xs: List[A], f: A -> Bool ! e) -> Bool ! e"),
    ("List", "find[A, e](xs: List[A], f: A -> Bool ! e) -> Opt[A] ! e"),
    ("List", "sort_by[A, K, e](xs: List[A], f: A -> K ! e) -> List[A] ! e"),
    ("List", "sum[A](xs: List[A]) -> A"),
    ("List", "push[A](xs: List[A], x: A) -> List[A]"),
    ("List", "concat[A](xs: List[A], ys: List[A]) -> List[A]"),
    ("List", "take[A](xs: List[A], n: Int) -> List[A]"),
    ("List", "drop[A](xs: List[A], n: Int) -> List[A]"),
    ("List", "reverse[A](xs: List[A]) -> List[A]"),
    ("List", "sort[A](xs: List[A]) -> List[A]"),
    ("List", "unique[A](xs: List[A]) -> List[A]"),
    ("List", "contains[A](xs: List[A], x: A) -> Bool"),
    ("List", "first[A](xs: List[A]) -> Opt[A]"),
    ("List", "last[A](xs: List[A]) -> Opt[A]"),
    ("List", "get[A](xs: List[A], i: Int) -> Opt[A]"),
    ("List", "min[A](xs: List[A]) -> Opt[A]"),
    ("List", "max[A](xs: List[A]) -> Opt[A]"),
    ("List", "counts[A](xs: List[A]) -> List[(A, Int)]"),
    ("List", "zip[A, B](xs: List[A], ys: List[B]) -> List[(A, B)]"),
    ("List", "enumerate[A](xs: List[A]) -> List[(Int, A)]"),
    ("List", "join(xs: List[Str], sep: Str) -> Str"),
    ("Str", "len(s: Str) -> Int"),
    ("Str", "is_empty(s: Str) -> Bool"),
    ("Str", "take(s: Str, n: Int) -> Str"),
    ("Str", "drop(s: Str, n: Int) -> Str"),
    ("Str", "reverse(s: Str) -> Str"),
    ("Str", "get(s: Str, i: Int) -> Opt[Str]"),
    ("Str", "first(s: Str) -> Opt[Str]"),
    ("Str", "last(s: Str) -> Opt[Str]"),
    ("Str", "lower(s: Str) -> Str"),
    ("Str", "upper(s: Str) -> Str"),
    ("Str", "trim(s: Str) -> Str"),
    ("Str", "split(s: Str, sep: Str) -> List[Str]"),
    ("Str", "words(s: Str) -> List[Str]"),
    ("Str", "chars(s: Str) -> List[Str]"),
    ("Str", "contains(s: Str, sub: Str) -> Bool"),
    ("Str", "starts_with(s: Str, p: Str) -> Bool"),
    ("Str", "ends_with(s: Str, p: Str) -> Bool"),
    ("Str", "replace(s: Str, from: Str, to: Str) -> Str"),
    ("Str", "repeat(s: Str, n: Int) -> Str"),
    ("Str", "to_int(s: Str) -> Opt[Int]"),
    ("Str", "is_alpha(s: Str) -> Bool"),
    ("Opt", "or_[A](o: Opt[A], d: A) -> A"),
    ("Opt", "is_some[A](o: Opt[A]) -> Bool"),
    ("Opt", "get[A](o: Opt[A]) -> A"),
    ("Opt", "is_none[A](o: Opt[A]) -> Bool"),
    ("Opt", "map[A, B, e](o: Opt[A], f: A -> B ! e) -> Opt[B] ! e"),
    ("Opt", "ok_or[A, E](o: Opt[A], e: E) -> A ! fail[E]"),
    ("Res", "is_ok[A, E](r: Res[A, E]) -> Bool"),
    ("Res", "get[A, E](r: Res[A, E]) -> A ! fail[E]"),
    ("Map", "get[K, V](m: Map[K, V], k: K) -> Opt[V]"),
    ("Map", "put[K, V](m: Map[K, V], k: K, v: V) -> Map[K, V]"),
    ("Map", "remove[K, V](m: Map[K, V], k: K) -> Map[K, V]"),
    ("Map", "has[K, V](m: Map[K, V], k: K) -> Bool"),
    ("Map", "keys[K, V](m: Map[K, V]) -> List[K]"),
    ("Map", "values[K, V](m: Map[K, V]) -> List[V]"),
    ("Map", "items[K, V](m: Map[K, V]) -> List[(K, V)]"),
    ("Map", "len[K, V](m: Map[K, V]) -> Int"),
    ("Secret", "map[A, B](s: Secret[A], f: A -> B) -> Secret[B]"),
    ("Secret", "check[A](s: Secret[A], f: A -> Bool) -> Bool"),
    ("Secret", "expose[A](s: Secret[A], reason: Str) -> A"),
    ("Pii", "map[A, B](p: Pii[A], f: A -> B) -> Pii[B]"),
    ("Pii", "expose[A](p: Pii[A], reason: Str) -> A"),
    ("Untrusted", "validate[A, B](u: Untrusted[A], f: A -> Opt[B]) -> Opt[B]"),
    ("Untrusted", "trust[A](u: Untrusted[A], reason: Str) -> A"),
    ("Guess", "conf[A](g: Guess[A]) -> F64"),
    ("Guess", "map[A, B](g: Guess[A], f: A -> B) -> Guess[B]"),
    ("Guess", "verify[A](g: Guess[A], f: A -> Bool) -> Opt[A]"),
    ("Guess", "at_least[A](g: Guess[A], min: F64) -> Opt[A]"),
    ("Guess", "accept[A](g: Guess[A], reason: Str) -> A"),
    ("Int", "abs(n: Int) -> Int"),
    ("Int", "to_f64(n: Int) -> F64"),
    ("F64", "abs(n: F64) -> F64"),
    ("F64", "round(n: F64) -> Int"),
    ("F64", "floor(n: F64) -> Int"),
    ("F64", "sqrt(n: F64) -> F64"),
    ("*", "str[A](x: A) -> Str"),
];

pub const SYS_GLOBALS: &[&str] = &[
    "alloc[T](n: Int, init: T) -> Ptr[T] ! unsafe",
    "free[T](p: Ptr[T]) -> Unit ! unsafe",
    "null[T]() -> Ptr[T]",
    "drop[A](x: A) -> Unit",
    "leak[A](x: A) -> Unit",
];

pub const SYS_METHODS: &[(&str, &str)] = &[
    ("Ptr", "load[T](p: Ptr[T], i: Int) -> T ! unsafe"),
    ("Ptr", "store_[T](p: Ptr[T], i: Int, x: T) -> Unit ! unsafe"),
    ("Ptr", "offset[T](p: Ptr[T], n: Int) -> Ptr[T] ! unsafe"),
    ("Ptr", "is_null[T](p: Ptr[T]) -> Bool"),
];
