pub const GLOBALS: &[&str] = &[
    "log(msg: Str) -> Unit ! log",
    "some[A](x: A) -> Opt[A]",
    "ok[A, E](x: A) -> Res[A, E]",
    "err[A, E](e: E) -> Res[A, E]",
    "empty_map[K, V]() -> Map[K, V]",
    "min[A](a: A, b: A) -> A",
    "max[A](a: A, b: A) -> A",
    "secret[A](x: A) -> Secret[A]",
    "pii[A](x: A) -> Pii[A]",
    "untrusted[A](x: A) -> Untrusted[A]",
    "guess[A](x: A, conf: F64) -> Guess[A]",
    "atomic(x: Int) -> Atomic[Int] ! conc",
    "chan[A]() -> Chan[A] ! conc",
];

pub const METHODS: &[(&str, &str)] = &[
    ("List", "len[A](xs: List[A]) -> Int"),
    ("List", "is_empty[A](xs: List[A]) -> Bool"),
    ("List", "map[A, B, e](xs: List[A], f: A -> B ! e) -> List[B] ! e"),
    ("List", "flat_map[A, B, e](xs: List[A], f: A -> List[B] ! e) -> List[B] ! e"),
    ("List", "filter[A, e](xs: List[A], f: A -> Bool ! e) -> List[A] ! e"),
    ("List", "fold[A, B, e](xs: List[A], init: B, f: (B, A) -> B ! e) -> B ! e"),
    ("List", "any[A, e](xs: List[A], f: A -> Bool ! e) -> Bool ! e"),
    ("List", "all[A, e](xs: List[A], f: A -> Bool ! e) -> Bool ! e"),
    ("List", "find[A, e](xs: List[A], f: A -> Bool ! e) -> Opt[A] ! e"),
    ("List", "sort_by[A, K, e](xs: List[A], f: A -> K ! e) -> List[A] ! e"),
    ("List", "sum[A](xs: List[A]) -> A"),
    ("List", "push[A](xs: List[A], x: A) -> List[A]"),
    ("List", "concat[A](xs: List[A], ys: List[A]) -> List[A]"),
    ("List", "take[A](xs: List[A], n: Int) -> List[A]"),
    ("List", "drop[A](xs: List[A], n: Int) -> List[A]"),
    ("List", "reverse[A](xs: List[A]) -> List[A]"),
    ("List", "sort[A](xs: List[A]) -> List[A]"),
    ("List", "unique[A](xs: List[A]) -> List[A]"),
    ("List", "contains[A](xs: List[A], x: A) -> Bool"),
    ("List", "first[A](xs: List[A]) -> Opt[A]"),
    ("List", "last[A](xs: List[A]) -> Opt[A]"),
    ("List", "get[A](xs: List[A], i: Int) -> Opt[A]"),
    ("List", "min[A](xs: List[A]) -> Opt[A]"),
    ("List", "max[A](xs: List[A]) -> Opt[A]"),
    ("List", "counts[A](xs: List[A]) -> List[(A, Int)]"),
    ("List", "zip[A, B](xs: List[A], ys: List[B]) -> List[(A, B)]"),
    ("List", "enumerate[A](xs: List[A]) -> List[(Int, A)]"),
    ("List", "join(xs: List[Str], sep: Str) -> Str"),
    ("Str", "len(s: Str) -> Int"),
    ("Str", "is_empty(s: Str) -> Bool"),
    ("Str", "take(s: Str, n: Int) -> Str"),
    ("Str", "drop(s: Str, n: Int) -> Str"),
    ("Str", "reverse(s: Str) -> Str"),
    ("Str", "get(s: Str, i: Int) -> Opt[Str]"),
    ("Str", "first(s: Str) -> Opt[Str]"),
    ("Str", "last(s: Str) -> Opt[Str]"),
    ("Str", "lower(s: Str) -> Str"),
    ("Str", "upper(s: Str) -> Str"),
    ("Str", "trim(s: Str) -> Str"),
    ("Str", "split(s: Str, sep: Str) -> List[Str]"),
    ("Str", "words(s: Str) -> List[Str]"),
    ("Str", "chars(s: Str) -> List[Str]"),
    ("Str", "contains(s: Str, sub: Str) -> Bool"),
    ("Str", "starts_with(s: Str, p: Str) -> Bool"),
    ("Str", "ends_with(s: Str, p: Str) -> Bool"),
    ("Str", "replace(s: Str, from: Str, to: Str) -> Str"),
    ("Str", "repeat(s: Str, n: Int) -> Str"),
    ("Str", "to_int(s: Str) -> Opt[Int]"),
    ("Str", "is_alpha(s: Str) -> Bool"),
    ("Str", "byte_len(s: Str) -> Int"),
    ("Str", "byte(s: Str, i: Int) -> Int"),
    ("Opt", "or_[A](o: Opt[A], d: A) -> A"),
    ("Opt", "is_some[A](o: Opt[A]) -> Bool"),
    ("Opt", "get[A](o: Opt[A]) -> A"),
    ("Opt", "is_none[A](o: Opt[A]) -> Bool"),
    ("Opt", "map[A, B, e](o: Opt[A], f: A -> B ! e) -> Opt[B] ! e"),
    ("Opt", "ok_or[A, E](o: Opt[A], e: E) -> A ! fail[E]"),
    ("Res", "is_ok[A, E](r: Res[A, E]) -> Bool"),
    ("Res", "get[A, E](r: Res[A, E]) -> A ! fail[E]"),
    ("Map", "get[K, V](m: Map[K, V], k: K) -> Opt[V]"),
    ("Map", "put[K, V](m: Map[K, V], k: K, v: V) -> Map[K, V]"),
    ("Map", "remove[K, V](m: Map[K, V], k: K) -> Map[K, V]"),
    ("Map", "has[K, V](m: Map[K, V], k: K) -> Bool"),
    ("Map", "keys[K, V](m: Map[K, V]) -> List[K]"),
    ("Map", "values[K, V](m: Map[K, V]) -> List[V]"),
    ("Map", "items[K, V](m: Map[K, V]) -> List[(K, V)]"),
    ("Map", "len[K, V](m: Map[K, V]) -> Int"),
    ("Secret", "map[A, B](s: Secret[A], f: A -> B) -> Secret[B]"),
    ("Secret", "check[A](s: Secret[A], f: A -> Bool) -> Bool"),
    ("Secret", "expose[A](s: Secret[A], reason: Str) -> A"),
    ("Pii", "map[A, B](p: Pii[A], f: A -> B) -> Pii[B]"),
    ("Pii", "expose[A](p: Pii[A], reason: Str) -> A"),
    ("Untrusted", "validate[A, B](u: Untrusted[A], f: A -> Opt[B]) -> Opt[B]"),
    ("Untrusted", "trust[A](u: Untrusted[A], reason: Str) -> A"),
    ("Guess", "conf[A](g: Guess[A]) -> F64"),
    ("Guess", "map[A, B](g: Guess[A], f: A -> B) -> Guess[B]"),
    ("Guess", "verify[A](g: Guess[A], f: A -> Bool) -> Opt[A]"),
    ("Guess", "at_least[A](g: Guess[A], min: F64) -> Opt[A]"),
    ("Guess", "accept[A](g: Guess[A], reason: Str) -> A"),
    ("Int", "abs(n: Int) -> Int"),
    ("Int", "to_f64(n: Int) -> F64"),
    ("Int", "band(a: Int, b: Int) -> Int"),
    ("Int", "bor(a: Int, b: Int) -> Int"),
    ("Int", "bxor(a: Int, b: Int) -> Int"),
    ("Int", "shl(a: Int, n: Int) -> Int"),
    ("Int", "shr(a: Int, n: Int) -> Int"),
    ("F64", "abs(n: F64) -> F64"),
    ("F64", "round(n: F64) -> Int"),
    ("F64", "floor(n: F64) -> Int"),
    ("F64", "sqrt(n: F64) -> F64"),
    ("Atomic", "load(a: Atomic[Int]) -> Int ! conc"),
    ("Atomic", "store_(a: Atomic[Int], v: Int) -> Unit ! conc"),
    ("Atomic", "add(a: Atomic[Int], d: Int) -> Unit ! conc"),
    ("Atomic", "cas(a: Atomic[Int], expect: Int, value: Int) -> Bool ! conc"),
    ("Chan", "send[A](c: Chan[A], x: A) -> Unit ! conc"),
    ("Chan", "recv[A](c: Chan[A]) -> Opt[A] ! conc"),
    ("Chan", "close[A](c: Chan[A]) -> Unit ! conc"),
    ("*", "str[A](x: A) -> Str"),
];

pub const STD_TYPES: &[(&str, &str, usize)] = &[("Set", "#Set", 1), ("Heap", "#Heap", 1), ("StrBuf", "#StrBuf", 0)];

pub const STD_GLOBALS: &[&str] = &[
    "empty_set[A]() -> Set[A]",
    "empty_heap[A]() -> Heap[A]",
    "str_buf() -> StrBuf",
    "range(start: Int, end: Int, step: Int) -> List[Int]",
    "clamp[A](x: A, lo: A, hi: A) -> A",
    "rand(seed: Int) -> (Int, Int)",
    "rand_int(seed: Int, lo: Int, hi: Int) -> (Int, Int)",
    "rand_f64(seed: Int) -> (F64, Int)",
    "from_bytes(bs: List[Int]) -> Opt[Str]",
    "from_codes(cs: List[Int]) -> Opt[Str]",
    "read_file(path: Str) -> Res[Str, Str] ! fs",
    "write_file(path: Str, s: Str) -> Res[Unit, Str] ! fs",
    "append_file(path: Str, s: Str) -> Res[Unit, Str] ! fs",
    "list_dir(path: Str) -> Res[List[Str], Str] ! fs",
    "read_line() -> Opt[Str] ! io",
    "read_lines() -> List[Str] ! io",
    "now_ms() -> Int ! time",
    "mono_ns() -> Int ! time",
    "sleep_ms(ms: Int) -> Unit ! time",
    "env_var(name: Str) -> Opt[Str] ! env",
    "args() -> List[Str] ! env",
];

pub const STD_METHODS: &[(&str, &str)] = &[
    ("List", "binary_search[A](xs: List[A], x: A) -> Opt[Int]"),
    ("List", "lower_bound[A](xs: List[A], x: A) -> Int"),
    ("List", "sort_with[A, e](xs: List[A], f: (A, A) -> Int ! e) -> List[A] ! e"),
    ("List", "chunks[A](xs: List[A], n: Int) -> List[List[A]]"),
    ("List", "windows[A](xs: List[A], n: Int) -> List[List[A]]"),
    ("List", "group_by[A, K, e](xs: List[A], f: A -> K ! e) -> List[(K, List[A])] ! e"),
    ("List", "partition[A, e](xs: List[A], f: A -> Bool ! e) -> (List[A], List[A]) ! e"),
    ("List", "scan[A, B, e](xs: List[A], init: B, f: (B, A) -> B ! e) -> List[B] ! e"),
    ("List", "flatten[A](xs: List[List[A]]) -> List[A]"),
    ("List", "index_of[A](xs: List[A], x: A) -> Opt[Int]"),
    ("List", "find_index[A, e](xs: List[A], f: A -> Bool ! e) -> Opt[Int] ! e"),
    ("List", "slice[A](xs: List[A], from: Int, to: Int) -> List[A]"),
    ("List", "push_front[A](xs: List[A], x: A) -> List[A]"),
    ("List", "pop_front[A](xs: List[A]) -> Opt[(A, List[A])]"),
    ("List", "pop_back[A](xs: List[A]) -> Opt[(A, List[A])]"),
    ("List", "to_set[A](xs: List[A]) -> Set[A]"),
    ("List", "to_heap[A](xs: List[A]) -> Heap[A]"),
    ("#Set", "add[A](s: Set[A], x: A) -> Set[A]"),
    ("#Set", "remove[A](s: Set[A], x: A) -> Set[A]"),
    ("#Set", "has[A](s: Set[A], x: A) -> Bool"),
    ("#Set", "len[A](s: Set[A]) -> Int"),
    ("#Set", "is_empty[A](s: Set[A]) -> Bool"),
    ("#Set", "items[A](s: Set[A]) -> List[A]"),
    ("#Set", "union[A](s: Set[A], t: Set[A]) -> Set[A]"),
    ("#Set", "inter[A](s: Set[A], t: Set[A]) -> Set[A]"),
    ("#Set", "diff[A](s: Set[A], t: Set[A]) -> Set[A]"),
    ("#Set", "min[A](s: Set[A]) -> Opt[A]"),
    ("#Set", "max[A](s: Set[A]) -> Opt[A]"),
    ("#Heap", "push[A](h: Heap[A], x: A) -> Heap[A]"),
    ("#Heap", "pop[A](h: Heap[A]) -> Opt[(A, Heap[A])]"),
    ("#Heap", "peek[A](h: Heap[A]) -> Opt[A]"),
    ("#Heap", "len[A](h: Heap[A]) -> Int"),
    ("#Heap", "is_empty[A](h: Heap[A]) -> Bool"),
    ("#Heap", "items[A](h: Heap[A]) -> List[A]"),
    ("#StrBuf", "add(b: StrBuf, s: Str) -> StrBuf"),
    ("#StrBuf", "byte_len(b: StrBuf) -> Int"),
    ("Str", "split_once(s: Str, sep: Str) -> Opt[(Str, Str)]"),
    ("Str", "index_of(s: Str, sub: Str) -> Opt[Int]"),
    ("Str", "pad_left(s: Str, n: Int, fill: Str) -> Str"),
    ("Str", "pad_right(s: Str, n: Int, fill: Str) -> Str"),
    ("Str", "to_f64(s: Str) -> Opt[F64]"),
    ("Str", "bytes(s: Str) -> List[Int]"),
    ("Str", "codes(s: Str) -> List[Int]"),
    ("F64", "fmt(x: F64, digits: Int) -> Str"),
    ("F64", "pow(x: F64, y: F64) -> F64"),
    ("F64", "exp(x: F64) -> F64"),
    ("F64", "ln(x: F64) -> F64"),
    ("F64", "log2(x: F64) -> F64"),
    ("F64", "log10(x: F64) -> F64"),
    ("F64", "sin(x: F64) -> F64"),
    ("F64", "cos(x: F64) -> F64"),
    ("F64", "tan(x: F64) -> F64"),
    ("F64", "asin(x: F64) -> F64"),
    ("F64", "acos(x: F64) -> F64"),
    ("F64", "atan(x: F64) -> F64"),
    ("F64", "atan2(y: F64, x: F64) -> F64"),
    ("F64", "hypot(x: F64, y: F64) -> F64"),
    ("F64", "ceil(x: F64) -> Int"),
    ("F64", "trunc(x: F64) -> Int"),
    ("F64", "is_nan(x: F64) -> Bool"),
    ("F64", "is_finite(x: F64) -> Bool"),
    ("Int", "gcd(a: Int, b: Int) -> Int"),
    ("Int", "lcm(a: Int, b: Int) -> Int"),
    ("Int", "wrapping_add(a: Int, b: Int) -> Int"),
    ("Int", "wrapping_sub(a: Int, b: Int) -> Int"),
    ("Int", "wrapping_mul(a: Int, b: Int) -> Int"),
    ("Int", "checked_add(a: Int, b: Int) -> Opt[Int]"),
    ("Int", "checked_sub(a: Int, b: Int) -> Opt[Int]"),
    ("Int", "checked_mul(a: Int, b: Int) -> Opt[Int]"),
    ("Int", "checked_div(a: Int, b: Int) -> Opt[Int]"),
    ("Int", "bnot(a: Int) -> Int"),
    ("Int", "popcount(a: Int) -> Int"),
    ("Int", "clz(a: Int) -> Int"),
    ("Int", "ctz(a: Int) -> Int"),
];

pub const STD_GLOBAL_NAMES: &[&str] = &[
    "empty_set", "empty_heap", "str_buf", "range", "clamp", "rand", "rand_int", "rand_f64", "from_bytes", "from_codes", "read_file", "write_file", "append_file", "list_dir", "read_line", "read_lines", "now_ms", "mono_ns", "sleep_ms", "env_var", "args",
];

pub const SYS_GLOBALS: &[&str] = &[
    "alloc[T](n: Int, init: T) -> Ptr[T] ! unsafe",
    "free[T](p: Ptr[T]) -> Unit ! unsafe",
    "null[T]() -> Ptr[T]",
    "drop[A](x: A) -> Unit",
    "leak[A](x: A) -> Unit",
];

pub const SYS_METHODS: &[(&str, &str)] = &[
    ("Ptr", "load[T](p: Ptr[T], i: Int) -> T ! unsafe"),
    ("Ptr", "store_[T](p: Ptr[T], i: Int, x: T) -> Unit ! unsafe"),
    ("Ptr", "offset[T](p: Ptr[T], n: Int) -> Ptr[T] ! unsafe"),
    ("Ptr", "is_null[T](p: Ptr[T]) -> Bool"),
];

pub const BARE_GLOBALS: &[&str] = &[
    "halt(code: Int) -> Unit ! mmio",
    "wait_irq() -> Unit ! mmio",
    "irq_enable(n: Int) -> Unit ! mmio",
    "timer_start(ticks: Int) -> Unit ! mmio",
    "ticks() -> Int ! mmio",
    "tick_hz() -> Int",
    "arch() -> Str",
];

pub const BARE_METHODS: &[(&str, &str)] = &[
    ("Mmio", "read[W](r: Mmio[W]) -> Int ! mmio"),
    ("Mmio", "write[W](r: Mmio[W], v: Int) -> Unit ! mmio"),
];

pub const BARE_NAMES: &[&str] = &["halt", "wait_irq", "irq_enable", "timer_start", "ticks", "tick_hz", "arch"];
