pub const GLOBALS: &[&str] = &[
    "log(msg: Str) -> Unit ! log",
    "some[A](x: A) -> Opt[A]",
    "ok[A, E](x: A) -> Res[A, E]",
    "err[A, E](e: E) -> Res[A, E]",
    "empty_map[K, V]() -> Map[K, V]",
    "min[A](a: A, b: A) -> A",
    "max[A](a: A, b: A) -> A",
    "secret[A](x: A) -> Secret[A]",
    "pii[A](x: A) -> Pii[A]",
    "untrusted[A](x: A) -> Untrusted[A]",
    "guess[A](x: A, conf: F64) -> Guess[A]",
    "atomic(x: Int) -> Atomic[Int] ! conc",
    "chan[A]() -> Chan[A] ! conc",
];

pub const METHODS: &[(&str, &str)] = &[
    ("List", "len[A](xs: List[A]) -> Int"),
    ("List", "is_empty[A](xs: List[A]) -> Bool"),
    ("List", "map[A, B, e](xs: List[A], f: A -> B ! e) -> List[B] ! e"),
    ("List", "flat_map[A, B, e](xs: List[A], f: A -> List[B] ! e) -> List[B] ! e"),
    ("List", "filter[A, e](xs: List[A], f: A -> Bool ! e) -> List[A] ! e"),
    ("List", "fold[A, B, e](xs: List[A], init: B, f: (B, A) -> B ! e) -> B ! e"),
    ("List", "any[A, e](xs: List[A], f: A -> Bool ! e) -> Bool ! e"),
    ("List", "all[A, e](xs: List[A], f: A -> Bool ! e) -> Bool ! e"),
    ("List", "find[A, e](xs: List[A], f: A -> Bool ! e) -> Opt[A] ! e"),
    ("List", "sort_by[A, K, e](xs: List[A], f: A -> K ! e) -> List[A] ! e"),
    ("List", "sum[A](xs: List[A]) -> A"),
    ("List", "push[A](xs: List[A], x: A) -> List[A]"),
    ("List", "concat[A](xs: List[A], ys: List[A]) -> List[A]"),
    ("List", "take[A](xs: List[A], n: Int) -> List[A]"),
    ("List", "drop[A](xs: List[A], n: Int) -> List[A]"),
    ("List", "reverse[A](xs: List[A]) -> List[A]"),
    ("List", "sort[A](xs: List[A]) -> List[A]"),
    ("List", "unique[A](xs: List[A]) -> List[A]"),
    ("List", "contains[A](xs: List[A], x: A) -> Bool"),
    ("List", "first[A](xs: List[A]) -> Opt[A]"),
    ("List", "last[A](xs: List[A]) -> Opt[A]"),
    ("List", "get[A](xs: List[A], i: Int) -> Opt[A]"),
    ("List", "min[A](xs: List[A]) -> Opt[A]"),
    ("List", "max[A](xs: List[A]) -> Opt[A]"),
    ("List", "counts[A](xs: List[A]) -> List[(A, Int)]"),
    ("List", "zip[A, B](xs: List[A], ys: List[B]) -> List[(A, B)]"),
    ("List", "enumerate[A](xs: List[A]) -> List[(Int, A)]"),
    ("List", "join(xs: List[Str], sep: Str) -> Str"),
    ("Str", "len(s: Str) -> Int"),
    ("Str", "is_empty(s: Str) -> Bool"),
    ("Str", "take(s: Str, n: Int) -> Str"),
    ("Str", "drop(s: Str, n: Int) -> Str"),
    ("Str", "reverse(s: Str) -> Str"),
    ("Str", "get(s: Str, i: Int) -> Opt[Str]"),
    ("Str", "first(s: Str) -> Opt[Str]"),
    ("Str", "last(s: Str) -> Opt[Str]"),
    ("Str", "lower(s: Str) -> Str"),
    ("Str", "upper(s: Str) -> Str"),
    ("Str", "trim(s: Str) -> Str"),
    ("Str", "split(s: Str, sep: Str) -> List[Str]"),
    ("Str", "words(s: Str) -> List[Str]"),
    ("Str", "chars(s: Str) -> List[Str]"),
    ("Str", "contains(s: Str, sub: Str) -> Bool"),
    ("Str", "starts_with(s: Str, p: Str) -> Bool"),
    ("Str", "ends_with(s: Str, p: Str) -> Bool"),
    ("Str", "replace(s: Str, from: Str, to: Str) -> Str"),
    ("Str", "repeat(s: Str, n: Int) -> Str"),
    ("Str", "to_int(s: Str) -> Opt[Int]"),
    ("Str", "is_alpha(s: Str) -> Bool"),
    ("Str", "byte_len(s: Str) -> Int"),
    ("Str", "byte(s: Str, i: Int) -> Int"),
    ("Opt", "or_[A](o: Opt[A], d: A) -> A"),
    ("Opt", "is_some[A](o: Opt[A]) -> Bool"),
    ("Opt", "get[A](o: Opt[A]) -> A"),
    ("Opt", "is_none[A](o: Opt[A]) -> Bool"),
    ("Opt", "map[A, B, e](o: Opt[A], f: A -> B ! e) -> Opt[B] ! e"),
    ("Opt", "ok_or[A, E](o: Opt[A], e: E) -> A ! fail[E]"),
    ("Res", "is_ok[A, E](r: Res[A, E]) -> Bool"),
    ("Res", "get[A, E](r: Res[A, E]) -> A ! fail[E]"),
    ("Map", "get[K, V](m: Map[K, V], k: K) -> Opt[V]"),
    ("Map", "put[K, V](m: Map[K, V], k: K, v: V) -> Map[K, V]"),
    ("Map", "remove[K, V](m: Map[K, V], k: K) -> Map[K, V]"),
    ("Map", "has[K, V](m: Map[K, V], k: K) -> Bool"),
    ("Map", "keys[K, V](m: Map[K, V]) -> List[K]"),
    ("Map", "values[K, V](m: Map[K, V]) -> List[V]"),
    ("Map", "items[K, V](m: Map[K, V]) -> List[(K, V)]"),
    ("Map", "len[K, V](m: Map[K, V]) -> Int"),
    ("Secret", "map[A, B](s: Secret[A], f: A -> B) -> Secret[B]"),
    ("Secret", "check[A](s: Secret[A], f: A -> Bool) -> Bool"),
    ("Secret", "expose[A](s: Secret[A], reason: Str) -> A"),
    ("Pii", "map[A, B](p: Pii[A], f: A -> B) -> Pii[B]"),
    ("Pii", "expose[A](p: Pii[A], reason: Str) -> A"),
    ("Untrusted", "validate[A, B](u: Untrusted[A], f: A -> Opt[B]) -> Opt[B]"),
    ("Untrusted", "trust[A](u: Untrusted[A], reason: Str) -> A"),
    ("Guess", "conf[A](g: Guess[A]) -> F64"),
    ("Guess", "map[A, B](g: Guess[A], f: A -> B) -> Guess[B]"),
    ("Guess", "verify[A](g: Guess[A], f: A -> Bool) -> Opt[A]"),
    ("Guess", "at_least[A](g: Guess[A], min: F64) -> Opt[A]"),
    ("Guess", "accept[A](g: Guess[A], reason: Str) -> A"),
    ("Int", "abs(n: Int) -> Int"),
    ("Int", "to_f64(n: Int) -> F64"),
    ("Int", "band(a: Int, b: Int) -> Int"),
    ("Int", "bor(a: Int, b: Int) -> Int"),
    ("Int", "bxor(a: Int, b: Int) -> Int"),
    ("Int", "shl(a: Int, n: Int) -> Int"),
    ("Int", "shr(a: Int, n: Int) -> Int"),
    ("F64", "abs(n: F64) -> F64"),
    ("F64", "round(n: F64) -> Int"),
    ("F64", "floor(n: F64) -> Int"),
    ("F64", "sqrt(n: F64) -> F64"),
    ("Atomic", "load(a: Atomic[Int]) -> Int ! conc"),
    ("Atomic", "store_(a: Atomic[Int], v: Int) -> Unit ! conc"),
    ("Atomic", "add(a: Atomic[Int], d: Int) -> Unit ! conc"),
    ("Atomic", "cas(a: Atomic[Int], expect: Int, value: Int) -> Bool ! conc"),
    ("Chan", "send[A](c: Chan[A], x: A) -> Unit ! conc"),
    ("Chan", "recv[A](c: Chan[A]) -> Opt[A] ! conc"),
    ("Chan", "close[A](c: Chan[A]) -> Unit ! conc"),
    ("*", "str[A](x: A) -> Str"),
];

pub const STD_TYPES: &[(&str, &str, usize)] = &[("Set", "#Set", 1), ("Heap", "#Heap", 1), ("StrBuf", "#StrBuf", 0), ("Time", "#Time", 0), ("Duration", "#Duration", 0), ("Bits", "#Bits", 0), ("HashMap", "#HashMap", 2), ("HashSet", "#HashSet", 1), ("BigInt", "#BigInt", 0), ("Dec", "#Dec", 0), ("Regex", "#Regex", 0)];

pub const STD_GLOBALS: &[&str] = &[
    "empty_set[A]() -> Set[A]",
    "empty_heap[A]() -> Heap[A]",
    "str_buf() -> StrBuf",
    "range(start: Int, end: Int, step: Int) -> List[Int]",
    "clamp[A](x: A, lo: A, hi: A) -> A",
    "rand(seed: Int) -> (Int, Int)",
    "rand_int(seed: Int, lo: Int, hi: Int) -> (Int, Int)",
    "rand_f64(seed: Int) -> (F64, Int)",
    "from_bytes(bs: List[Int]) -> Opt[Str]",
    "from_codes(cs: List[Int]) -> Opt[Str]",
    "read_file(path: Str) -> Res[Str, Str] ! fs",
    "write_file(path: Str, s: Str) -> Res[Unit, Str] ! fs",
    "append_file(path: Str, s: Str) -> Res[Unit, Str] ! fs",
    "list_dir(path: Str) -> Res[List[Str], Str] ! fs",
    "remove_file(path: Str) -> Res[Unit, Str] ! fs",
    "read_bytes(path: Str) -> Res[List[Int], Str] ! fs",
    "write_bytes(path: Str, bs: List[Int]) -> Res[Unit, Str] ! fs",
    "mkdir(path: Str) -> Res[Unit, Str] ! fs",
    "mkdir_all(path: Str) -> Res[Unit, Str] ! fs",
    "remove_dir(path: Str) -> Res[Unit, Str] ! fs",
    "rename(from: Str, to: Str) -> Res[Unit, Str] ! fs",
    "exists(path: Str) -> Bool ! fs",
    "is_dir(path: Str) -> Bool ! fs",
    "file_size(path: Str) -> Res[Int, Str] ! fs",
    "modified_ms(path: Str) -> Res[Int, Str] ! fs",
    "eprint(s: Str) -> Unit ! io",
    "run_cmd(prog: Str, args: List[Str], input: Str) -> Res[(Int, Str, Str), Str] ! proc",
    "read_line() -> Opt[Str] ! io",
    "read_lines() -> List[Str] ! io",
    "now_ms() -> Int ! time",
    "mono_ns() -> Int ! time",
    "sleep_ms(ms: Int) -> Unit ! time",
    "env_var(name: Str) -> Opt[Str] ! env",
    "args() -> List[Str] ! env",
    "rand_normal(seed: Int, mean: F64, sd: F64) -> (F64, Int)",
    "rand_uniform(seed: Int, lo: F64, hi: F64) -> (F64, Int)",
    "rand_exp(seed: Int, rate: F64) -> (F64, Int)",
    "rand_bool(seed: Int, p: F64) -> (Bool, Int)",
    "bits(n: Int) -> Bits",
    "regex(p: Str) -> Res[Regex, Str]",
    "big(n: Int) -> BigInt",
    "parse_big(s: Str) -> Opt[BigInt]",
    "decimal(s: Str) -> Opt[Dec]",
    "hash_map[K, V]() -> HashMap[K, V]",
    "hash_set[A]() -> HashSet[A]",
    "time_ms(ms: Int) -> Time",
    "date(y: Int, m: Int, d: Int) -> Opt[Time]",
    "datetime(y: Int, mo: Int, d: Int, h: Int, mi: Int, s: Int) -> Opt[Time]",
    "parse_time(s: Str) -> Opt[Time]",
    "now() -> Time ! time",
    "millis(n: Int) -> Duration",
    "secs(n: Int) -> Duration",
    "mins(n: Int) -> Duration",
    "hours(n: Int) -> Duration",
    "days(n: Int) -> Duration",
    "pi() -> F64",
    "euler() -> F64",
    "inf() -> F64",
    "nan() -> F64",
];

pub const STD_METHODS: &[(&str, &str)] = &[
    ("List", "binary_search[A](xs: List[A], x: A) -> Opt[Int]"),
    ("List", "lower_bound[A](xs: List[A], x: A) -> Int"),
    ("List", "sort_with[A, e](xs: List[A], f: (A, A) -> Int ! e) -> List[A] ! e"),
    ("List", "chunks[A](xs: List[A], n: Int) -> List[List[A]]"),
    ("List", "windows[A](xs: List[A], n: Int) -> List[List[A]]"),
    ("List", "group_by[A, K, e](xs: List[A], f: A -> K ! e) -> List[(K, List[A])] ! e"),
    ("List", "partition[A, e](xs: List[A], f: A -> Bool ! e) -> (List[A], List[A]) ! e"),
    ("List", "scan[A, B, e](xs: List[A], init: B, f: (B, A) -> B ! e) -> List[B] ! e"),
    ("List", "flatten[A](xs: List[List[A]]) -> List[A]"),
    ("List", "index_of[A](xs: List[A], x: A) -> Opt[Int]"),
    ("List", "find_index[A, e](xs: List[A], f: A -> Bool ! e) -> Opt[Int] ! e"),
    ("List", "slice[A](xs: List[A], from: Int, to: Int) -> List[A]"),
    ("List", "push_front[A](xs: List[A], x: A) -> List[A]"),
    ("List", "pop_front[A](xs: List[A]) -> Opt[(A, List[A])]"),
    ("List", "pop_back[A](xs: List[A]) -> Opt[(A, List[A])]"),
    ("List", "to_set[A](xs: List[A]) -> Set[A]"),
    ("List", "to_heap[A](xs: List[A]) -> Heap[A]"),
    ("List", "shuffle[A](xs: List[A], seed: Int) -> List[A]"),
    ("List", "choice[A](xs: List[A], seed: Int) -> Opt[A]"),
    ("Res", "is_err[A, E](r: Res[A, E]) -> Bool"),
    ("Res", "or_[A, E](r: Res[A, E], d: A) -> A"),
    ("Res", "map[A, B, E, e](r: Res[A, E], f: A -> B ! e) -> Res[B, E] ! e"),
    ("#Set", "add[A](s: Set[A], x: A) -> Set[A]"),
    ("#Set", "remove[A](s: Set[A], x: A) -> Set[A]"),
    ("#Set", "has[A](s: Set[A], x: A) -> Bool"),
    ("#Set", "len[A](s: Set[A]) -> Int"),
    ("#Set", "is_empty[A](s: Set[A]) -> Bool"),
    ("#Set", "items[A](s: Set[A]) -> List[A]"),
    ("#Set", "union[A](s: Set[A], t: Set[A]) -> Set[A]"),
    ("#Set", "inter[A](s: Set[A], t: Set[A]) -> Set[A]"),
    ("#Set", "diff[A](s: Set[A], t: Set[A]) -> Set[A]"),
    ("#Set", "min[A](s: Set[A]) -> Opt[A]"),
    ("#Set", "max[A](s: Set[A]) -> Opt[A]"),
    ("#Heap", "push[A](h: Heap[A], x: A) -> Heap[A]"),
    ("#Heap", "pop[A](h: Heap[A]) -> Opt[(A, Heap[A])]"),
    ("#Heap", "peek[A](h: Heap[A]) -> Opt[A]"),
    ("#Heap", "len[A](h: Heap[A]) -> Int"),
    ("#Heap", "is_empty[A](h: Heap[A]) -> Bool"),
    ("#Heap", "items[A](h: Heap[A]) -> List[A]"),
    ("#StrBuf", "add(b: StrBuf, s: Str) -> StrBuf"),
    ("#StrBuf", "byte_len(b: StrBuf) -> Int"),
    ("Str", "split_once(s: Str, sep: Str) -> Opt[(Str, Str)]"),
    ("Str", "index_of(s: Str, sub: Str) -> Opt[Int]"),
    ("Str", "pad_left(s: Str, n: Int, fill: Str) -> Str"),
    ("Str", "pad_right(s: Str, n: Int, fill: Str) -> Str"),
    ("Str", "to_f64(s: Str) -> Opt[F64]"),
    ("Str", "bytes(s: Str) -> List[Int]"),
    ("Str", "codes(s: Str) -> List[Int]"),
    ("F64", "fmt(x: F64, digits: Int) -> Str"),
    ("F64", "pow(x: F64, y: F64) -> F64"),
    ("F64", "exp(x: F64) -> F64"),
    ("F64", "ln(x: F64) -> F64"),
    ("F64", "log2(x: F64) -> F64"),
    ("F64", "log10(x: F64) -> F64"),
    ("F64", "sin(x: F64) -> F64"),
    ("F64", "cos(x: F64) -> F64"),
    ("F64", "tan(x: F64) -> F64"),
    ("F64", "asin(x: F64) -> F64"),
    ("F64", "acos(x: F64) -> F64"),
    ("F64", "atan(x: F64) -> F64"),
    ("F64", "atan2(y: F64, x: F64) -> F64"),
    ("F64", "hypot(x: F64, y: F64) -> F64"),
    ("F64", "ceil(x: F64) -> Int"),
    ("F64", "trunc(x: F64) -> Int"),
    ("F64", "is_nan(x: F64) -> Bool"),
    ("F64", "is_finite(x: F64) -> Bool"),
    ("Int", "gcd(a: Int, b: Int) -> Int"),
    ("Int", "lcm(a: Int, b: Int) -> Int"),
    ("Int", "wrapping_add(a: Int, b: Int) -> Int"),
    ("Int", "wrapping_sub(a: Int, b: Int) -> Int"),
    ("Int", "wrapping_mul(a: Int, b: Int) -> Int"),
    ("Int", "checked_add(a: Int, b: Int) -> Opt[Int]"),
    ("Int", "checked_sub(a: Int, b: Int) -> Opt[Int]"),
    ("Int", "checked_mul(a: Int, b: Int) -> Opt[Int]"),
    ("Int", "checked_div(a: Int, b: Int) -> Opt[Int]"),
    ("Int", "bnot(a: Int) -> Int"),
    ("Int", "popcount(a: Int) -> Int"),
    ("Int", "clz(a: Int) -> Int"),
    ("Int", "ctz(a: Int) -> Int"),
    ("Int", "format(n: Int, spec: Str) -> Str"),
    ("F64", "format(x: F64, spec: Str) -> Str"),
    ("Str", "format(s: Str, spec: Str) -> Str"),
    ("#HashMap", "get[K, V](m: HashMap[K, V], k: K) -> Opt[V]"),
    ("#HashMap", "put[K, V](m: HashMap[K, V], k: K, v: V) -> HashMap[K, V]"),
    ("#HashMap", "remove[K, V](m: HashMap[K, V], k: K) -> HashMap[K, V]"),
    ("#HashMap", "has[K, V](m: HashMap[K, V], k: K) -> Bool"),
    ("#HashMap", "keys[K, V](m: HashMap[K, V]) -> List[K]"),
    ("#HashMap", "values[K, V](m: HashMap[K, V]) -> List[V]"),
    ("#HashMap", "items[K, V](m: HashMap[K, V]) -> List[(K, V)]"),
    ("#HashMap", "len[K, V](m: HashMap[K, V]) -> Int"),
    ("#HashMap", "is_empty[K, V](m: HashMap[K, V]) -> Bool"),
    ("#HashSet", "add[A](s: HashSet[A], x: A) -> HashSet[A]"),
    ("#HashSet", "remove[A](s: HashSet[A], x: A) -> HashSet[A]"),
    ("#HashSet", "has[A](s: HashSet[A], x: A) -> Bool"),
    ("#HashSet", "len[A](s: HashSet[A]) -> Int"),
    ("#HashSet", "is_empty[A](s: HashSet[A]) -> Bool"),
    ("#HashSet", "items[A](s: HashSet[A]) -> List[A]"),
    ("#HashSet", "union[A](s: HashSet[A], t: HashSet[A]) -> HashSet[A]"),
    ("#HashSet", "inter[A](s: HashSet[A], t: HashSet[A]) -> HashSet[A]"),
    ("#HashSet", "diff[A](s: HashSet[A], t: HashSet[A]) -> HashSet[A]"),
    ("List", "to_hash_set[A](xs: List[A]) -> HashSet[A]"),
    ("List", "to_hash_map[K, V](xs: List[(K, V)]) -> HashMap[K, V]"),
    ("#BigInt", "add(a: BigInt, b: BigInt) -> BigInt"),
    ("#BigInt", "sub(a: BigInt, b: BigInt) -> BigInt"),
    ("#BigInt", "mul(a: BigInt, b: BigInt) -> BigInt"),
    ("#BigInt", "div(a: BigInt, b: BigInt) -> BigInt"),
    ("#BigInt", "rem(a: BigInt, b: BigInt) -> BigInt"),
    ("#BigInt", "divmod(a: BigInt, b: BigInt) -> (BigInt, BigInt)"),
    ("#BigInt", "pow(a: BigInt, e: Int) -> BigInt"),
    ("#BigInt", "neg(a: BigInt) -> BigInt"),
    ("#BigInt", "abs(a: BigInt) -> BigInt"),
    ("#BigInt", "sign(a: BigInt) -> Int"),
    ("#BigInt", "to_int(a: BigInt) -> Opt[Int]"),
    ("#BigInt", "to_f64(a: BigInt) -> F64"),
    ("#BigInt", "to_dec(a: BigInt) -> Dec"),
    ("#Dec", "add(a: Dec, b: Dec) -> Dec"),
    ("#Dec", "sub(a: Dec, b: Dec) -> Dec"),
    ("#Dec", "mul(a: Dec, b: Dec) -> Dec"),
    ("#Dec", "div(a: Dec, b: Dec, scale: Int) -> Dec"),
    ("#Dec", "round(a: Dec, scale: Int) -> Dec"),
    ("#Dec", "scale(a: Dec) -> Int"),
    ("#Dec", "neg(a: Dec) -> Dec"),
    ("#Dec", "abs(a: Dec) -> Dec"),
    ("#Dec", "sign(a: Dec) -> Int"),
    ("#Dec", "to_f64(a: Dec) -> F64"),
    ("#Regex", "is_match(r: Regex, s: Str) -> Bool"),
    ("#Regex", "find(r: Regex, s: Str) -> Opt[Str]"),
    ("#Regex", "span(r: Regex, s: Str) -> Opt[(Int, Int)]"),
    ("#Regex", "find_all(r: Regex, s: Str) -> List[Str]"),
    ("#Regex", "captures(r: Regex, s: Str) -> Opt[List[Str]]"),
    ("#Regex", "replace(r: Regex, s: Str, rep: Str) -> Str"),
    ("#Regex", "split(r: Regex, s: Str) -> List[Str]"),
    ("#Bits", "has(b: Bits, i: Int) -> Bool"),
    ("#Bits", "set(b: Bits, i: Int) -> Bits"),
    ("#Bits", "clear(b: Bits, i: Int) -> Bits"),
    ("#Bits", "flip(b: Bits, i: Int) -> Bits"),
    ("#Bits", "len(b: Bits) -> Int"),
    ("#Bits", "count(b: Bits) -> Int"),
    ("#Bits", "union(b: Bits, c: Bits) -> Bits"),
    ("#Bits", "inter(b: Bits, c: Bits) -> Bits"),
    ("#Bits", "diff(b: Bits, c: Bits) -> Bits"),
    ("#Bits", "xor(b: Bits, c: Bits) -> Bits"),
    ("#Bits", "flip_all(b: Bits) -> Bits"),
    ("#Bits", "items(b: Bits) -> List[Int]"),
    ("List", "to_bits(xs: List[Int], n: Int) -> Bits"),
    ("#Time", "unix_ms(t: Time) -> Int"),
    ("#Time", "year(t: Time) -> Int"),
    ("#Time", "month(t: Time) -> Int"),
    ("#Time", "day(t: Time) -> Int"),
    ("#Time", "hour(t: Time) -> Int"),
    ("#Time", "minute(t: Time) -> Int"),
    ("#Time", "second(t: Time) -> Int"),
    ("#Time", "milli(t: Time) -> Int"),
    ("#Time", "weekday(t: Time) -> Int"),
    ("#Time", "yday(t: Time) -> Int"),
    ("#Time", "date(t: Time) -> Time"),
    ("#Time", "iso(t: Time) -> Str"),
    ("#Time", "format(t: Time, pat: Str) -> Str"),
    ("#Time", "add(t: Time, d: Duration) -> Time"),
    ("#Time", "sub(t: Time, d: Duration) -> Time"),
    ("#Time", "since(t: Time, u: Time) -> Duration"),
    ("#Time", "add_months(t: Time, n: Int) -> Time"),
    ("#Time", "add_years(t: Time, n: Int) -> Time"),
    ("#Duration", "ms(d: Duration) -> Int"),
    ("#Duration", "secs(d: Duration) -> Int"),
    ("#Duration", "mins(d: Duration) -> Int"),
    ("#Duration", "hours(d: Duration) -> Int"),
    ("#Duration", "days(d: Duration) -> Int"),
    ("#Duration", "add(d: Duration, e: Duration) -> Duration"),
    ("#Duration", "sub(d: Duration, e: Duration) -> Duration"),
    ("#Duration", "mul(d: Duration, k: Int) -> Duration"),
    ("#Duration", "div(d: Duration, k: Int) -> Duration"),
    ("#Duration", "neg(d: Duration) -> Duration"),
    ("#Duration", "abs(d: Duration) -> Duration"),
    ("Int", "rotl(a: Int, n: Int) -> Int"),
    ("Int", "rotr(a: Int, n: Int) -> Int"),
    ("Int", "byteswap(a: Int) -> Int"),
    ("Int", "saturating_add(a: Int, b: Int) -> Int"),
    ("Int", "saturating_sub(a: Int, b: Int) -> Int"),
    ("Int", "saturating_mul(a: Int, b: Int) -> Int"),
    ("F64", "sinh(x: F64) -> F64"),
    ("F64", "cosh(x: F64) -> F64"),
    ("F64", "tanh(x: F64) -> F64"),
    ("F64", "asinh(x: F64) -> F64"),
    ("F64", "acosh(x: F64) -> F64"),
    ("F64", "atanh(x: F64) -> F64"),
    ("F64", "cbrt(x: F64) -> F64"),
    ("F64", "exp2(x: F64) -> F64"),
    ("F64", "expm1(x: F64) -> F64"),
    ("F64", "log1p(x: F64) -> F64"),
    ("F64", "erf(x: F64) -> F64"),
    ("F64", "erfc(x: F64) -> F64"),
    ("F64", "gamma(x: F64) -> F64"),
    ("F64", "lgamma(x: F64) -> F64"),
    ("F64", "fmod(x: F64, y: F64) -> F64"),
    ("F64", "remainder(x: F64, y: F64) -> F64"),
    ("F64", "copysign(x: F64, y: F64) -> F64"),
    ("F64", "nextafter(x: F64, y: F64) -> F64"),
    ("F64", "fdim(x: F64, y: F64) -> F64"),
    ("F64", "fma(x: F64, y: F64, z: F64) -> F64"),
    ("F64", "is_inf(x: F64) -> Bool"),
];

pub const STD_GLOBAL_NAMES: &[&str] = &[
    "empty_set", "empty_heap", "str_buf", "range", "clamp", "rand", "rand_int", "rand_f64", "from_bytes", "from_codes", "read_file", "write_file", "append_file", "list_dir", "remove_file", "read_line", "read_lines", "now_ms", "mono_ns", "sleep_ms", "env_var", "args", "pi", "euler", "inf", "nan", "rand_normal", "rand_uniform", "rand_exp", "rand_bool", "read_bytes", "write_bytes", "mkdir", "mkdir_all", "remove_dir", "rename", "exists", "is_dir", "file_size", "modified_ms", "eprint", "run_cmd", "regex", "bits", "big", "parse_big", "decimal", "hash_map", "hash_set", "time_ms", "date", "datetime", "parse_time", "now", "millis", "secs", "mins", "hours", "days",
];

pub const SYS_GLOBALS: &[&str] = &[
    "alloc[T](n: Int, init: T) -> Ptr[T] ! unsafe",
    "free[T](p: Ptr[T]) -> Unit ! unsafe",
    "null[T]() -> Ptr[T]",
    "drop[A](x: A) -> Unit",
    "leak[A](x: A) -> Unit",
];

pub const SYS_METHODS: &[(&str, &str)] = &[
    ("Ptr", "load[T](p: Ptr[T], i: Int) -> T ! unsafe"),
    ("Ptr", "store_[T](p: Ptr[T], i: Int, x: T) -> Unit ! unsafe"),
    ("Ptr", "offset[T](p: Ptr[T], n: Int) -> Ptr[T] ! unsafe"),
    ("Ptr", "is_null[T](p: Ptr[T]) -> Bool"),
];

pub const BARE_GLOBALS: &[&str] = &[
    "halt(code: Int) -> Unit ! mmio",
    "wait_irq() -> Unit ! mmio",
    "irq_enable(n: Int) -> Unit ! mmio",
    "timer_start(ticks: Int) -> Unit ! mmio",
    "ticks() -> Int ! mmio",
    "tick_hz() -> Int",
    "arch() -> Str",
];

pub const BARE_METHODS: &[(&str, &str)] = &[
    ("Mmio", "read[W](r: Mmio[W]) -> Int ! mmio"),
    ("Mmio", "write[W](r: Mmio[W], v: Int) -> Unit ! mmio"),
];

pub const BARE_NAMES: &[&str] = &["halt", "wait_irq", "irq_enable", "timer_start", "ticks", "tick_hz", "arch"];
