[package]
name = "sspur-wasm"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
sspur-syntax.workspace = true
sspur-check.workspace = true
sspur-eval = { path = "../sspur-eval", default-features = false }
serde_json.workspace = true
wasm-bindgen = "0.2"
