[package]
name = "sspur-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "sspur"
path = "src/main.rs"

[dependencies]
sspur-syntax.workspace = true
sspur-check.workspace = true
sspur-hash.workspace = true
sspur-eval.workspace = true
sspur-store.workspace = true
sspur-native.workspace = true
serde_json.workspace = true
