use std::path::{Path, PathBuf};
use std::process::Command;

fn root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join("../..")
}

fn sspur(dir: &Path, args: &[&str]) -> (String, String, bool) {
    let o = Command::new(env!("CARGO_BIN_EXE_sspur")).args(args).current_dir(dir).output().unwrap();
    (String::from_utf8_lossy(&o.stdout).into_owned(), String::from_utf8_lossy(&o.stderr).into_owned(), o.status.success())
}

fn scratch(name: &str) -> PathBuf {
    let d = std::env::temp_dir().join(format!("sspur-ffi-{name}-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&d);
    std::fs::create_dir_all(&d).unwrap();
    d
}

const BOUND: &str = r#"// generated by sspur bind from sample.h
extern fn add(a: I32, b: I32) -> I32 ! ffi from "sample"
extern fn scale(x: F64, k: F32) -> F64 ! ffi from "sample"
extern fn count_char(s: Str, c: I8) -> U64 ! ffi from "sample"
extern fn greeting() -> Opt[Str] ! ffi from "sample"
extern fn dup_upper(s: Str) -> Opt[Str] ! ffi from "sample"
extern fn sum64(xs: List[Int], n: U64) -> Int ! ffi from "sample"
extern fn is_even(n: Int) -> Bool ! ffi from "sample"
extern fn reset() ! ffi from "sample"
extern fn clamp_byte(v: I32) -> U8 ! ffi from "sample"
extern fn set_flag(f: U32, bit: U16) -> U32 ! ffi from "sample"
extern fn c_min(a: I32, b: I32) -> I32 ! ffi from "sample" as "min"
// skipped 4 declaration(s):
//   printf_like: variadic
//   make_point: result type struct point (unsupported type)
//   fill: parameter out has type int * (mutable pointer)
//   helper: static, no linkable symbol
"#;

#[test]
fn bind_generates_externs_from_a_header() {
    let d = scratch("bind");
    let h = root().join("crates/sspur-cli/tests/ffi/sample.h");
    let (out, err, ok) = sspur(&d, &["bind", h.to_str().unwrap(), "--lib", "sample"]);
    assert!(ok, "{err}");
    // long is 32 bits on Windows (LLP64).
    let want = if cfg!(windows) { BOUND.replace("is_even(n: Int)", "is_even(n: I32)") } else { BOUND.to_string() };
    assert_eq!(out, want);
    std::fs::write(d.join("bound.ssp"), &out).unwrap();
    let (out, err, ok) = sspur(&d, &["check", "bound.ssp"]);
    assert!(ok, "{out}{err}");
    let (out, _, _) = sspur(&d, &["fmt", "bound.ssp"]);
    assert!(out.contains("extern fn c_min(a: I32, b: I32) -> I32 ! ffi from \"sample\" as \"min\"\n"), "{out}");
}

const PROG: &str = r#"extern fn cbrt(x: F64) -> F64 ! ffi from "m"
extern fn hypotf(x: F32, y: F32) -> F32 ! ffi from "m"
extern fn abs(x: I32) -> I32 ! ffi
extern fn strlen(s: Str) -> U64 ! ffi
extern fn strnlen(s: List[U8], n: U64) -> U64 ! ffi
extern fn getenv(name: Str) -> Opt[Str] ! ffi
extern fn must_getenv(name: Str) -> Str ! ffi as "getenv"
extern fn strtoull(s: Str, end: Int, base: I32) -> U64 ! ffi
extern fn setlocale(cat: I32, loc: Opt[Str]) -> Opt[Str] ! ffi
extern fn toupper(c: I32) -> I32 ! ffi

fn shout(s: Str) -> Str ! ffi
= s.chars.map(c => if c == "a" then "A" else c).join("") + "{toupper(98)}"

fn total(xs: List[Str]) -> Int ! ffi
= xs.map(strlen).sum

test roots = (cbrt(27.0) - 3.0).abs < 0.000000001 and hypotf(3.0, 4.0) == 5.0
test ints = abs(-5) == 5 and strlen("hello") == 5 and total(["ab", "cde"]) == 5
test bytes = strnlen([104, 105, 0, 33], 4) == 2
test env = getenv("SSPUR_FFI_UNSET_VAR").is_none
test locale = setlocale(0, none) == some("C")
test upper = shout("banana") == "bAnAnA66"
test range = abs(3000000000) == 1
test null = must_getenv("SSPUR_FFI_UNSET_VAR") == ""
test big = strtoull("18446744073709551615", 0, 10) == 0
test elem = strnlen([300], 1) == 0
"#;

#[test]
fn extern_calls_agree_across_tiers() {
    let d = scratch("tiers");
    std::fs::write(d.join("p.ssp"), PROG).unwrap();
    let expect = "FAIL  range: ffi: argument x of abs is out of range for I32 (value = 3000000000)
FAIL  null: ffi: must_getenv returned a null string
FAIL  big: ffi: result of strtoull is out of range for Int (value = 18446744073709551615)
FAIL  elem: ffi: argument s of strnlen has an element out of range for U8 (value = 300)
6 passed, 4 failed
";
    for tier in ["--interp", "--release", "--native"] {
        let (out, err, _) = sspur(&d, &["test", tier, "p.ssp"]);
        assert_eq!(out, expect, "{tier}: {err}");
    }
    let (out, _, _) = sspur(&d, &["native", "--release", "p.ssp"]);
    assert!(!out.contains("interp "), "{out}");
    assert_eq!(out.matches("native  ").count(), 12, "{out}");
}

#[test]
fn extern_declarations_are_checked() {
    let d = scratch("check");
    let cases = [
        ("extern fn cbrt(x: F64) -> F64 ! ffi from \"m\"\n\nfn f() -> F64\n= cbrt(8.0)\n", "E_EFFECT_MISSING performs 'ffi'"),
        ("extern fn f() -> Int\n", "E_EXTERN extern functions declare exactly the effect 'ffi'"),
        ("extern fn f(x: List[Str]) -> Int ! ffi\n", "E_EXTERN parameter 'x': type List[Str] cannot cross the C boundary"),
        ("extern fn f(x: Int) -> Int ! ffi\n  pre x > 0\n", "E_PARSE_EXTERN extern functions have no contracts"),
    ];
    for (src, want) in cases {
        std::fs::write(d.join("c.ssp"), src).unwrap();
        let (out, err, ok) = sspur(&d, &["check", "c.ssp"]);
        assert!(!ok && err.contains(want), "{src}: {out}{err}");
    }
}

#[test]
fn export_c_round_trips_through_a_c_program() {
    let d = scratch("export");
    let ex = root().join("examples/ffi");
    let (out, err, ok) = sspur(&d, &["export-c", ex.join("geo.ssp").to_str().unwrap(), "-o", "libgeo"]);
    assert!(ok, "{out}{err}");
    let (lib, hint) = if cfg!(windows) { ("libgeo.lib", "link with libgeo.lib") } else { ("libgeo.a", "link with -L. -lgeo -lm") };
    assert!(out.contains("export  geo_label\n") && out.contains(hint), "{out}");
    assert!(d.join(lib).exists() && d.join("libgeo.h").exists());
    let cc = sspur_native::cgen::flags::cc();
    let link: Vec<String> = if cfg!(windows) {
        ["-D_CRT_SECURE_NO_WARNINGS".to_string(), "libgeo.lib".into()].into_iter().chain(sspur_native::cgen::flags::sys_libs()).collect()
    } else {
        ["-L.", "-lgeo", "-lm", "-lpthread"].map(String::from).to_vec()
    };
    let exe = format!("geo{}", std::env::consts::EXE_SUFFIX);
    let o = Command::new(&cc).args(["-Wall", "-Werror", "-I."]).arg(ex.join("main.c")).args(&link).args(["-o", &exe]).current_dir(&d).output().unwrap();
    assert!(o.status.success(), "{}", String::from_utf8_lossy(&o.stderr));
    let o = Command::new(d.join(&exe)).env("HOME", "/tmp").output().unwrap();
    assert_eq!(
        String::from_utf8_lossy(&o.stdout).replace("\r\n", "\n"),
        "dist = 5
cube_side = 3
cube_side failed (100): unhandled error: BadInput{what: \"negative volume -8.0\"}
parse_sum = 42
label = geo:3:7
steps failed (3): contract violated: pre n >= 0 in steps (n = -1)
fact failed (1): integer overflow
fact(20) = 2432902008176640000
has_home = true
"
    );
    let (out, err, ok) = sspur(&d, &["test", ex.join("geo.ssp").to_str().unwrap()]);
    assert!(ok, "{out}{err}");
    let (out, err, ok) = sspur(&d, &["export-c", ex.join("geo.ssp").to_str().unwrap(), "-o", "libgeo", "--shared"]);
    assert!(ok && d.join(format!("libgeo.{}", std::env::consts::DLL_EXTENSION)).exists(), "{out}{err}");
}
